// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyApp.Infrastructure.Persistence.CompiledModel
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c6cc668c-0427-4786-b00f-c64e5615e002"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var order = OrderEntityType.Create(this);
            var orderLine = OrderLineEntityType.Create(this);

            OrderLineEntityType.CreateForeignKey1(orderLine, order);

            OrderEntityType.CreateAnnotations(order);
            OrderLineEntityType.CreateAnnotations(orderLine);

            AddAnnotation("ProductVersion", "10.0.7");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var order = FindEntityType("MyApp.Domain.Order")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            order.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var myAppDomainOrderTableBase = new TableBase("MyApp.Domain.Order", null, relationalModel);
            var customerIdColumnBase = new ColumnBase<ColumnMappingBase>("CustomerId", "INTEGER", myAppDomainOrderTableBase);
            myAppDomainOrderTableBase.Columns.Add("CustomerId", customerIdColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", myAppDomainOrderTableBase);
            myAppDomainOrderTableBase.Columns.Add("Id", idColumnBase);
            var statusColumnBase = new ColumnBase<ColumnMappingBase>("Status", "TEXT", myAppDomainOrderTableBase);
            myAppDomainOrderTableBase.Columns.Add("Status", statusColumnBase);
            var totalColumnBase = new ColumnBase<ColumnMappingBase>("Total", "TEXT", myAppDomainOrderTableBase);
            myAppDomainOrderTableBase.Columns.Add("Total", totalColumnBase);
            relationalModel.DefaultTables.Add("MyApp.Domain.Order", myAppDomainOrderTableBase);
            var myAppDomainOrderMappingBase = new TableMappingBase<ColumnMappingBase>(order, myAppDomainOrderTableBase, null);
            myAppDomainOrderTableBase.AddTypeMapping(myAppDomainOrderMappingBase, false);
            defaultTableMappings.Add(myAppDomainOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, order.FindProperty("Id")!, myAppDomainOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)customerIdColumnBase, order.FindProperty("CustomerId")!, myAppDomainOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)statusColumnBase, order.FindProperty("Status")!, myAppDomainOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)totalColumnBase, order.FindProperty("Total")!, myAppDomainOrderMappingBase);

            var tableMappings = new List<TableMapping>();
            order.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var ordersTable = new Table("Orders", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", ordersTable);
            ordersTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            var customerIdColumn = new Column("CustomerId", "INTEGER", ordersTable);
            ordersTable.Columns.Add("CustomerId", customerIdColumn);
            customerIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(customerIdColumn);
            var statusColumn = new Column("Status", "TEXT", ordersTable);
            ordersTable.Columns.Add("Status", statusColumn);
            statusColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(statusColumn);
            var totalColumn = new Column("Total", "TEXT", ordersTable);
            ordersTable.Columns.Add("Total", totalColumn);
            totalColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(totalColumn);
            relationalModel.Tables.Add(("Orders", null), ordersTable);
            var ordersTableMapping = new TableMapping(order, ordersTable, null);
            ordersTable.AddTypeMapping(ordersTableMapping, false);
            tableMappings.Add(ordersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, order.FindProperty("Id")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(customerIdColumn, order.FindProperty("CustomerId")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(statusColumn, order.FindProperty("Status")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(totalColumn, order.FindProperty("Total")!, ordersTableMapping);
            var pK_Orders = new UniqueConstraint("PK_Orders", ordersTable, new[] { idColumn });
            ordersTable.PrimaryKey = pK_Orders;
            pK_Orders.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Orders));
            var pK_OrdersKey = RelationalModel.GetKey(this,
                "MyApp.Domain.Order",
                new[] { "Id" });
            pK_Orders.MappedKeys.Add(pK_OrdersKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_OrdersKey).Add(pK_Orders);
            ordersTable.UniqueConstraints.Add("PK_Orders", pK_Orders);

            var orderLine = FindEntityType("MyApp.Domain.OrderLine")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            orderLine.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var myAppDomainOrderLineTableBase = new TableBase("MyApp.Domain.OrderLine", null, relationalModel);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", myAppDomainOrderLineTableBase);
            myAppDomainOrderLineTableBase.Columns.Add("Id", idColumnBase0);
            var orderIdColumnBase = new ColumnBase<ColumnMappingBase>("OrderId", "INTEGER", myAppDomainOrderLineTableBase);
            myAppDomainOrderLineTableBase.Columns.Add("OrderId", orderIdColumnBase);
            var priceColumnBase = new ColumnBase<ColumnMappingBase>("Price", "TEXT", myAppDomainOrderLineTableBase);
            myAppDomainOrderLineTableBase.Columns.Add("Price", priceColumnBase);
            var quantityColumnBase = new ColumnBase<ColumnMappingBase>("Quantity", "INTEGER", myAppDomainOrderLineTableBase);
            myAppDomainOrderLineTableBase.Columns.Add("Quantity", quantityColumnBase);
            var skuColumnBase = new ColumnBase<ColumnMappingBase>("Sku", "TEXT", myAppDomainOrderLineTableBase);
            myAppDomainOrderLineTableBase.Columns.Add("Sku", skuColumnBase);
            relationalModel.DefaultTables.Add("MyApp.Domain.OrderLine", myAppDomainOrderLineTableBase);
            var myAppDomainOrderLineMappingBase = new TableMappingBase<ColumnMappingBase>(orderLine, myAppDomainOrderLineTableBase, null);
            myAppDomainOrderLineTableBase.AddTypeMapping(myAppDomainOrderLineMappingBase, false);
            defaultTableMappings0.Add(myAppDomainOrderLineMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, orderLine.FindProperty("Id")!, myAppDomainOrderLineMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderIdColumnBase, orderLine.FindProperty("OrderId")!, myAppDomainOrderLineMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)priceColumnBase, orderLine.FindProperty("Price")!, myAppDomainOrderLineMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityColumnBase, orderLine.FindProperty("Quantity")!, myAppDomainOrderLineMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)skuColumnBase, orderLine.FindProperty("Sku")!, myAppDomainOrderLineMappingBase);

            var tableMappings0 = new List<TableMapping>();
            orderLine.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var orderLinesTable = new Table("OrderLines", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", orderLinesTable);
            orderLinesTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn0);
            var orderIdColumn = new Column("OrderId", "INTEGER", orderLinesTable);
            orderLinesTable.Columns.Add("OrderId", orderIdColumn);
            orderIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(orderIdColumn);
            var priceColumn = new Column("Price", "TEXT", orderLinesTable);
            orderLinesTable.Columns.Add("Price", priceColumn);
            priceColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(priceColumn);
            var quantityColumn = new Column("Quantity", "INTEGER", orderLinesTable);
            orderLinesTable.Columns.Add("Quantity", quantityColumn);
            quantityColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(quantityColumn);
            var skuColumn = new Column("Sku", "TEXT", orderLinesTable);
            orderLinesTable.Columns.Add("Sku", skuColumn);
            skuColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(skuColumn);
            relationalModel.Tables.Add(("OrderLines", null), orderLinesTable);
            var orderLinesTableMapping = new TableMapping(orderLine, orderLinesTable, null);
            orderLinesTable.AddTypeMapping(orderLinesTableMapping, false);
            tableMappings0.Add(orderLinesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, orderLine.FindProperty("Id")!, orderLinesTableMapping);
            RelationalModel.CreateColumnMapping(orderIdColumn, orderLine.FindProperty("OrderId")!, orderLinesTableMapping);
            RelationalModel.CreateColumnMapping(priceColumn, orderLine.FindProperty("Price")!, orderLinesTableMapping);
            RelationalModel.CreateColumnMapping(quantityColumn, orderLine.FindProperty("Quantity")!, orderLinesTableMapping);
            RelationalModel.CreateColumnMapping(skuColumn, orderLine.FindProperty("Sku")!, orderLinesTableMapping);
            var pK_OrderLines = new UniqueConstraint("PK_OrderLines", orderLinesTable, new[] { idColumn0 });
            orderLinesTable.PrimaryKey = pK_OrderLines;
            pK_OrderLines.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_OrderLines));
            var pK_OrderLinesKey = RelationalModel.GetKey(this,
                "MyApp.Domain.OrderLine",
                new[] { "Id" });
            pK_OrderLines.MappedKeys.Add(pK_OrderLinesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_OrderLinesKey).Add(pK_OrderLines);
            orderLinesTable.UniqueConstraints.Add("PK_OrderLines", pK_OrderLines);
            var iX_OrderLines_OrderId = new TableIndex(
            "IX_OrderLines_OrderId", orderLinesTable, new[] { orderIdColumn }, false);
            iX_OrderLines_OrderId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<int>(iX_OrderLines_OrderId));
            var iX_OrderLines_OrderIdIx = RelationalModel.GetIndex(this,
                "MyApp.Domain.OrderLine",
                new[] { "OrderId" });
            iX_OrderLines_OrderId.MappedIndexes.Add(iX_OrderLines_OrderIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_OrderLines_OrderIdIx).Add(iX_OrderLines_OrderId);
            orderLinesTable.Indexes.Add("IX_OrderLines_OrderId", iX_OrderLines_OrderId);
            var fK_OrderLines_Orders_OrderId = new ForeignKeyConstraint(
                "FK_OrderLines_Orders_OrderId", orderLinesTable, ordersTable,
                new[] { orderIdColumn },
                ordersTable.FindUniqueConstraint("PK_Orders")!, ReferentialAction.Cascade);
            fK_OrderLines_Orders_OrderId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<int, int>(fK_OrderLines_Orders_OrderId));
            var fK_OrderLines_Orders_OrderIdFk = RelationalModel.GetForeignKey(this,
                "MyApp.Domain.OrderLine",
                new[] { "OrderId" },
                "MyApp.Domain.Order",
                new[] { "Id" });
            fK_OrderLines_Orders_OrderId.MappedForeignKeys.Add(fK_OrderLines_Orders_OrderIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_OrderLines_Orders_OrderIdFk).Add(fK_OrderLines_Orders_OrderId);
            orderLinesTable.ForeignKeyConstraints.Add(fK_OrderLines_Orders_OrderId);
            ordersTable.ReferencingForeignKeyConstraints.Add(fK_OrderLines_Orders_OrderId);
            return relationalModel.MakeReadOnly();
        }
    }
}
