CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529114155_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "Status" character varying(32) NOT NULL,
        "Total" text NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529114155_InitialCreate') THEN
    CREATE TABLE "OrderLines" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Sku" character varying(64) NOT NULL,
        "Quantity" integer NOT NULL,
        "Price" text NOT NULL,
        "OrderId" integer NOT NULL,
        CONSTRAINT "PK_OrderLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderLines_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529114155_InitialCreate') THEN
    CREATE INDEX "IX_OrderLines_OrderId" ON "OrderLines" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529114155_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260529114155_InitialCreate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

