CREATE TABLE "Customers" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Customers" PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Email" TEXT NOT NULL
);

CREATE TABLE "Orders" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Orders" PRIMARY KEY,
    "CustomerId" INTEGER NOT NULL,
    "Total" TEXT NOT NULL,
    "Status" TEXT NOT NULL
);
