// <auto-generated />
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using MyApp.Domain;
using MyApp.Domain.ValueObjects;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyApp.Infrastructure.Persistence.CompiledModel
{
    public static class OrderUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref OrderId Id(Order @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CustomerId>k__BackingField")]
        public static extern ref CustomerId CustomerId(Order @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref OrderStatus Status(Order @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Total>k__BackingField")]
        public static extern ref Money Total(Order @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_lines")]
        public static extern ref List<OrderLine> _lines(Order @this);
    }
}
