// <auto-generated />
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Domain;
using MyApp.Domain.ValueObjects;
using MyApp.Infrastructure.Persistence.Configurations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyApp.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class OrderLineEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MyApp.Domain.OrderLine",
                typeof(OrderLine),
                baseEntityType,
                propertyCount: 5,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && entry.ReadShadowValue<int>(0) == 0 ? entry.ReadTemporaryValue<int>(0) : entry.ReadShadowValue<int>(0))),
                int (IInternalEntry entry) => entry.ReadShadowValue<int>(0),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: 0,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var orderId = runtimeEntityType.AddProperty(
                "OrderId",
                typeof(OrderId));
            orderId.SetAccessors(
                OrderId (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<OrderId>(1) : (entry.FlaggedAsTemporary(1) && entry.ReadShadowValue<OrderId>(1).Equals(default(OrderId)) ? entry.ReadTemporaryValue<OrderId>(1) : entry.ReadShadowValue<OrderId>(1))),
                OrderId (IInternalEntry entry) => entry.ReadShadowValue<OrderId>(1),
                OrderId (IInternalEntry entry) => entry.ReadOriginalValue<OrderId>(orderId, 1),
                OrderId (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<OrderId>(orderId, 1));
            orderId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: 1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            orderId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<OrderId>(
                    bool (OrderId v1, OrderId v2) => v1.Equals(v2),
                    int (OrderId v) => ((object)v).GetHashCode(),
                    OrderId (OrderId v) => v),
                keyComparer: new ValueComparer<OrderId>(
                    bool (OrderId v1, OrderId v2) => v1.Equals(v2),
                    int (OrderId v) => ((object)v).GetHashCode(),
                    OrderId (OrderId v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<OrderId, int>(
                    int (OrderId id) => id.Value,
                    OrderId (int v) => new OrderId(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<OrderId, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<OrderId, int>(
                        int (OrderId id) => id.Value,
                        OrderId (int v) => new OrderId(v))));
            orderId.SetCurrentValueComparer(new CurrentProviderValueComparer<OrderId, int>(orderId));
            orderId.SetSentinelFromProviderValue(0);

            var price = runtimeEntityType.AddProperty(
                "Price",
                typeof(Money),
                propertyInfo: typeof(OrderLine).GetProperty("Price", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OrderLine).GetField("<Price>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            price.SetGetter(
                Money (OrderLine instance) => OrderLineUnsafeAccessors.Price(instance),
                bool (OrderLine instance) => OrderLineUnsafeAccessors.Price(instance).Equals(default(Money)));
            price.SetSetter(
                OrderLine (OrderLine instance, Money value) =>
                {
                    OrderLineUnsafeAccessors.Price(instance) = value;
                    return instance;
                });
            price.SetMaterializationSetter(
                OrderLine (OrderLine instance, Money value) =>
                {
                    OrderLineUnsafeAccessors.Price(instance) = value;
                    return instance;
                });
            price.SetAccessors(
                Money (IInternalEntry entry) => OrderLineUnsafeAccessors.Price(((OrderLine)(entry.Entity))),
                Money (IInternalEntry entry) => OrderLineUnsafeAccessors.Price(((OrderLine)(entry.Entity))),
                Money (IInternalEntry entry) => entry.ReadOriginalValue<Money>(price, 2),
                Money (IInternalEntry entry) => entry.GetCurrentValue<Money>(price));
            price.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            price.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<Money>(
                    bool (Money v1, Money v2) => v1.Equals(v2),
                    int (Money v) => ((object)v).GetHashCode(),
                    Money (Money v) => v),
                keyComparer: new ValueComparer<Money>(
                    bool (Money v1, Money v2) => v1.Equals(v2),
                    int (Money v) => ((object)v).GetHashCode(),
                    Money (Money v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<Money, string>(
                    string (Money m) => m.Amount.ToString(CultureInfo.InvariantCulture) + "|" + m.Currency,
                    Money (string s) => OrderConfiguration.FromString(s)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Money, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<Money, string>(
                        string (Money m) => m.Amount.ToString(CultureInfo.InvariantCulture) + "|" + m.Currency,
                        Money (string s) => OrderConfiguration.FromString(s))));
            price.SetSentinelFromProviderValue("0|");
            price.AddAnnotation("Relational:ColumnName", "Price");

            var quantity = runtimeEntityType.AddProperty(
                "Quantity",
                typeof(int),
                propertyInfo: typeof(OrderLine).GetProperty("Quantity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OrderLine).GetField("<Quantity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            quantity.SetGetter(
                int (OrderLine instance) => OrderLineUnsafeAccessors.Quantity(instance),
                bool (OrderLine instance) => OrderLineUnsafeAccessors.Quantity(instance) == 0);
            quantity.SetSetter(
                OrderLine (OrderLine instance, int value) =>
                {
                    OrderLineUnsafeAccessors.Quantity(instance) = value;
                    return instance;
                });
            quantity.SetMaterializationSetter(
                OrderLine (OrderLine instance, int value) =>
                {
                    OrderLineUnsafeAccessors.Quantity(instance) = value;
                    return instance;
                });
            quantity.SetAccessors(
                int (IInternalEntry entry) => OrderLineUnsafeAccessors.Quantity(((OrderLine)(entry.Entity))),
                int (IInternalEntry entry) => OrderLineUnsafeAccessors.Quantity(((OrderLine)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(quantity, 3),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(quantity));
            quantity.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            quantity.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var sku = runtimeEntityType.AddProperty(
                "Sku",
                typeof(string),
                propertyInfo: typeof(OrderLine).GetProperty("Sku", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OrderLine).GetField("<Sku>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            sku.SetGetter(
                string (OrderLine instance) => OrderLineUnsafeAccessors.Sku(instance),
                bool (OrderLine instance) => OrderLineUnsafeAccessors.Sku(instance) == null);
            sku.SetSetter(
                OrderLine (OrderLine instance, string value) =>
                {
                    OrderLineUnsafeAccessors.Sku(instance) = value;
                    return instance;
                });
            sku.SetMaterializationSetter(
                OrderLine (OrderLine instance, string value) =>
                {
                    OrderLineUnsafeAccessors.Sku(instance) = value;
                    return instance;
                });
            sku.SetAccessors(
                string (IInternalEntry entry) => OrderLineUnsafeAccessors.Sku(((OrderLine)(entry.Entity))),
                string (IInternalEntry entry) => OrderLineUnsafeAccessors.Sku(((OrderLine)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(sku, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(sku));
            sku.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            sku.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { orderId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true,
                ownership: true);

            var lines = principalEntityType.AddNavigation("Lines",
                runtimeForeignKey,
                onDependent: false,
                typeof(IReadOnlyList<OrderLine>),
                propertyInfo: typeof(Order).GetProperty("Lines", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("_lines", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                eagerLoaded: true);

            lines.SetGetter(
                IReadOnlyList<OrderLine> (Order instance) => (OrderUnsafeAccessors._lines(instance) == null ? null : ((IReadOnlyList<OrderLine>)(OrderUnsafeAccessors._lines(instance)))),
                bool (Order instance) => OrderUnsafeAccessors._lines(instance) == null);
            lines.SetSetter(
                Order (Order instance, IReadOnlyList<OrderLine> value) =>
                {
                    OrderUnsafeAccessors._lines(instance) = ((List<OrderLine>)value);
                    return instance;
                });
            lines.SetMaterializationSetter(
                Order (Order instance, IReadOnlyList<OrderLine> value) =>
                {
                    OrderUnsafeAccessors._lines(instance) = ((List<OrderLine>)value);
                    return instance;
                });
            lines.SetAccessors(
                IReadOnlyList<OrderLine> (IInternalEntry entry) => ((IReadOnlyList<OrderLine>)(OrderUnsafeAccessors._lines(((Order)(entry.Entity))))),
                IReadOnlyList<OrderLine> (IInternalEntry entry) => ((IReadOnlyList<OrderLine>)(OrderUnsafeAccessors._lines(((Order)(entry.Entity))))),
                null,
                IReadOnlyList<OrderLine> (IInternalEntry entry) => entry.GetCurrentValue<IReadOnlyList<OrderLine>>(lines));
            lines.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            lines.SetCollectionAccessor<Order, List<OrderLine>, OrderLine>(
                List<OrderLine> (Order entity) => OrderUnsafeAccessors._lines(entity),
                (Order entity, List<OrderLine> collection) => OrderUnsafeAccessors._lines(entity) = ((List<OrderLine>)collection),
                (Order entity, List<OrderLine> collection) => OrderUnsafeAccessors._lines(entity) = ((List<OrderLine>)collection),
                List<OrderLine> (Order entity, Action<Order, List<OrderLine>> setter) => ClrCollectionAccessorFactory.CreateAndSet<Order, List<OrderLine>, List<OrderLine>>(entity, setter),
                List<OrderLine> () => new List<OrderLine>());
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var orderId = runtimeEntityType.FindProperty("OrderId");
            var price = runtimeEntityType.FindProperty("Price");
            var quantity = runtimeEntityType.FindProperty("Quantity");
            var sku = runtimeEntityType.FindProperty("Sku");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((OrderLine)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, OrderId, Money, int, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<OrderId>)(((IProperty)orderId).GetValueComparer())).Snapshot(source.GetCurrentValue<OrderId>(orderId)), ((ValueComparer<Money>)(((IProperty)price).GetValueComparer())).Snapshot(source.GetCurrentValue<Money>(price)), ((ValueComparer<int>)(((IProperty)quantity).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(quantity)), (source.GetCurrentValue<string>(sku) == null ? null : ((ValueComparer<string>)(((IProperty)sku).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(sku))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, OrderId>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<OrderId>)(((IProperty)orderId).GetValueComparer())).Snapshot(default(OrderId))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, OrderId>(default(int), default(OrderId)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<int, OrderId>((source.ContainsKey("Id") ? ((int)(source["Id"])) : 0), (source.ContainsKey("OrderId") ? ((OrderId)(source["OrderId"])) : default(OrderId))))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, OrderId>(default(int), default(OrderId)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((OrderLine)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, OrderId>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<OrderId>)(((IProperty)orderId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<OrderId>(orderId)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 2,
                relationshipCount: 2,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "OrderLines");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
