// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using MyApp.Domain;
using MyApp.Domain.ValueObjects;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyApp.Infrastructure.Persistence.CompiledModel
{
    public static class OrderLineUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Price>k__BackingField")]
        public static extern ref Money Price(OrderLine @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Quantity>k__BackingField")]
        public static extern ref int Quantity(OrderLine @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Sku>k__BackingField")]
        public static extern ref string Sku(OrderLine @this);
    }
}
