// <auto-generated />
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using MyApp.Domain;
using MyApp.Domain.ValueObjects;
using MyApp.Infrastructure.Persistence.Configurations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyApp.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class OrderEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MyApp.Domain.Order",
                typeof(Order),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(OrderId),
                propertyInfo: typeof(Order).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetGetter(
                OrderId (Order instance) => OrderUnsafeAccessors.Id(instance),
                bool (Order instance) => OrderUnsafeAccessors.Id(instance).Equals(default(OrderId)));
            id.SetSetter(
                Order (Order instance, OrderId value) =>
                {
                    OrderUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                Order (Order instance, OrderId value) =>
                {
                    OrderUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                OrderId (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<OrderId>(0) : (entry.FlaggedAsTemporary(0) && OrderUnsafeAccessors.Id(((Order)(entry.Entity))).Equals(default(OrderId)) ? entry.ReadTemporaryValue<OrderId>(0) : OrderUnsafeAccessors.Id(((Order)(entry.Entity))))),
                OrderId (IInternalEntry entry) => OrderUnsafeAccessors.Id(((Order)(entry.Entity))),
                OrderId (IInternalEntry entry) => entry.ReadOriginalValue<OrderId>(id, 0),
                OrderId (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<OrderId>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<OrderId>(
                    bool (OrderId v1, OrderId v2) => v1.Equals(v2),
                    int (OrderId v) => ((object)v).GetHashCode(),
                    OrderId (OrderId v) => v),
                keyComparer: new ValueComparer<OrderId>(
                    bool (OrderId v1, OrderId v2) => v1.Equals(v2),
                    int (OrderId v) => ((object)v).GetHashCode(),
                    OrderId (OrderId v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<OrderId, int>(
                    int (OrderId id) => id.Value,
                    OrderId (int v) => new OrderId(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<OrderId, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<OrderId, int>(
                        int (OrderId id) => id.Value,
                        OrderId (int v) => new OrderId(v))));
            id.SetCurrentValueComparer(new CurrentProviderValueComparer<OrderId, int>(id));
            id.SetSentinelFromProviderValue(0);

            var customerId = runtimeEntityType.AddProperty(
                "CustomerId",
                typeof(CustomerId),
                propertyInfo: typeof(Order).GetProperty("CustomerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<CustomerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            customerId.SetGetter(
                CustomerId (Order instance) => OrderUnsafeAccessors.CustomerId(instance),
                bool (Order instance) => OrderUnsafeAccessors.CustomerId(instance).Equals(default(CustomerId)));
            customerId.SetSetter(
                Order (Order instance, CustomerId value) =>
                {
                    OrderUnsafeAccessors.CustomerId(instance) = value;
                    return instance;
                });
            customerId.SetMaterializationSetter(
                Order (Order instance, CustomerId value) =>
                {
                    OrderUnsafeAccessors.CustomerId(instance) = value;
                    return instance;
                });
            customerId.SetAccessors(
                CustomerId (IInternalEntry entry) => OrderUnsafeAccessors.CustomerId(((Order)(entry.Entity))),
                CustomerId (IInternalEntry entry) => OrderUnsafeAccessors.CustomerId(((Order)(entry.Entity))),
                CustomerId (IInternalEntry entry) => entry.ReadOriginalValue<CustomerId>(customerId, 1),
                CustomerId (IInternalEntry entry) => entry.GetCurrentValue<CustomerId>(customerId));
            customerId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            customerId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<CustomerId>(
                    bool (CustomerId v1, CustomerId v2) => v1.Equals(v2),
                    int (CustomerId v) => ((object)v).GetHashCode(),
                    CustomerId (CustomerId v) => v),
                keyComparer: new ValueComparer<CustomerId>(
                    bool (CustomerId v1, CustomerId v2) => v1.Equals(v2),
                    int (CustomerId v) => ((object)v).GetHashCode(),
                    CustomerId (CustomerId v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<CustomerId, int>(
                    int (CustomerId id) => id.Value,
                    CustomerId (int v) => new CustomerId(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<CustomerId, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<CustomerId, int>(
                        int (CustomerId id) => id.Value,
                        CustomerId (int v) => new CustomerId(v))));
            customerId.SetSentinelFromProviderValue(0);

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(OrderStatus),
                propertyInfo: typeof(Order).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32,
                providerPropertyType: typeof(string));
            status.SetGetter(
                OrderStatus (Order instance) => OrderUnsafeAccessors.Status(instance),
                bool (Order instance) => object.Equals(((object)(OrderUnsafeAccessors.Status(instance))), ((object)(OrderStatus.Pending))));
            status.SetSetter(
                Order (Order instance, OrderStatus value) =>
                {
                    OrderUnsafeAccessors.Status(instance) = value;
                    return instance;
                });
            status.SetMaterializationSetter(
                Order (Order instance, OrderStatus value) =>
                {
                    OrderUnsafeAccessors.Status(instance) = value;
                    return instance;
                });
            status.SetAccessors(
                OrderStatus (IInternalEntry entry) => OrderUnsafeAccessors.Status(((Order)(entry.Entity))),
                OrderStatus (IInternalEntry entry) => OrderUnsafeAccessors.Status(((Order)(entry.Entity))),
                OrderStatus (IInternalEntry entry) => entry.ReadOriginalValue<OrderStatus>(status, 2),
                OrderStatus (IInternalEntry entry) => entry.GetCurrentValue<OrderStatus>(status));
            status.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            status.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<OrderStatus>(
                    bool (OrderStatus v1, OrderStatus v2) => object.Equals(((object)v1), ((object)v2)),
                    int (OrderStatus v) => ((object)v).GetHashCode(),
                    OrderStatus (OrderStatus v) => v),
                keyComparer: new ValueComparer<OrderStatus>(
                    bool (OrderStatus v1, OrderStatus v2) => object.Equals(((object)v1), ((object)v2)),
                    int (OrderStatus v) => ((object)v).GetHashCode(),
                    OrderStatus (OrderStatus v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<OrderStatus, string>(
                    string (OrderStatus v) => ((object)v).ToString(),
                    OrderStatus (string v) => StringEnumConverter<OrderStatus, string, OrderStatus>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<OrderStatus, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<OrderStatus, string>(
                        string (OrderStatus v) => ((object)v).ToString(),
                        OrderStatus (string v) => StringEnumConverter<OrderStatus, string, OrderStatus>.ConvertToEnum(v))));
            status.SetSentinelFromProviderValue("Pending");

            var total = runtimeEntityType.AddProperty(
                "Total",
                typeof(Money),
                propertyInfo: typeof(Order).GetProperty("Total", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<Total>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            total.SetGetter(
                Money (Order instance) => OrderUnsafeAccessors.Total(instance),
                bool (Order instance) => OrderUnsafeAccessors.Total(instance).Equals(default(Money)));
            total.SetSetter(
                Order (Order instance, Money value) =>
                {
                    OrderUnsafeAccessors.Total(instance) = value;
                    return instance;
                });
            total.SetMaterializationSetter(
                Order (Order instance, Money value) =>
                {
                    OrderUnsafeAccessors.Total(instance) = value;
                    return instance;
                });
            total.SetAccessors(
                Money (IInternalEntry entry) => OrderUnsafeAccessors.Total(((Order)(entry.Entity))),
                Money (IInternalEntry entry) => OrderUnsafeAccessors.Total(((Order)(entry.Entity))),
                Money (IInternalEntry entry) => entry.ReadOriginalValue<Money>(total, 3),
                Money (IInternalEntry entry) => entry.GetCurrentValue<Money>(total));
            total.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            total.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<Money>(
                    bool (Money v1, Money v2) => v1.Equals(v2),
                    int (Money v) => ((object)v).GetHashCode(),
                    Money (Money v) => v),
                keyComparer: new ValueComparer<Money>(
                    bool (Money v1, Money v2) => v1.Equals(v2),
                    int (Money v) => ((object)v).GetHashCode(),
                    Money (Money v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<Money, string>(
                    string (Money m) => m.Amount.ToString(CultureInfo.InvariantCulture) + "|" + m.Currency,
                    Money (string s) => OrderConfiguration.FromString(s)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Money, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<Money, string>(
                        string (Money m) => m.Amount.ToString(CultureInfo.InvariantCulture) + "|" + m.Currency,
                        Money (string s) => OrderConfiguration.FromString(s))));
            total.SetSentinelFromProviderValue("0|");
            total.AddAnnotation("Relational:ColumnName", "Total");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var customerId = runtimeEntityType.FindProperty("CustomerId");
            var status = runtimeEntityType.FindProperty("Status");
            var total = runtimeEntityType.FindProperty("Total");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<OrderId>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<OrderId>(key));
            var lines = runtimeEntityType.FindNavigation("Lines");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Order)(source.Entity));
                    return ((ISnapshot)(new Snapshot<OrderId, CustomerId, OrderStatus, Money>(((ValueComparer<OrderId>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<OrderId>(id)), ((ValueComparer<CustomerId>)(((IProperty)customerId).GetValueComparer())).Snapshot(source.GetCurrentValue<CustomerId>(customerId)), ((ValueComparer<OrderStatus>)(((IProperty)status).GetValueComparer())).Snapshot(source.GetCurrentValue<OrderStatus>(status)), ((ValueComparer<Money>)(((IProperty)total).GetValueComparer())).Snapshot(source.GetCurrentValue<Money>(total)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<OrderId>(((ValueComparer<OrderId>)(((IProperty)id).GetValueComparer())).Snapshot(default(OrderId))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<OrderId>(default(OrderId)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Order)(source.Entity));
                    return ((ISnapshot)(new Snapshot<OrderId, object>(((ValueComparer<OrderId>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<OrderId>(id)), SnapshotFactoryFactory.SnapshotCollection(source.GetCurrentValue<IReadOnlyList<OrderLine>>(lines)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Orders");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
