<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyApp.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ZeroAlloc.Resilience" />
    <PackageReference Include="ZeroAlloc.Rest" />
    <PackageReference Include="ZeroAlloc.Rest.SystemTextJson" />
    <PackageReference Include="ZeroAlloc.Rest.Resilience" />
    <PackageReference Include="ZeroAlloc.Inject" />
    <PackageReference Include="ZeroAlloc.Inject.Generator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="../MyApp.Application/MyApp.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MyApp.Api" />
  </ItemGroup>
</Project>
