// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MyApp.Persistence;
using MyApp.Persistence.CompiledModel;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
