// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyApp.Persistence.CompiledModel
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("eff06b8c-ffff-48be-a4d6-7f9a1fe36eb0"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var customer = CustomerEntityType.Create(this);
            var order = OrderEntityType.Create(this);

            CustomerEntityType.CreateAnnotations(customer);
            OrderEntityType.CreateAnnotations(order);

            AddAnnotation("ProductVersion", "10.0.8");
        }
    }
}
