CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "Status" character varying(32) NOT NULL,
    "Total" text NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE "OrderLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sku" character varying(64) NOT NULL,
    "Quantity" integer NOT NULL CHECK ("Quantity" > 0),
    "Price" text NOT NULL,
    "OrderId" integer NOT NULL,
    CONSTRAINT "PK_OrderLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderLines_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrderLines_OrderId" ON "OrderLines" ("OrderId");
